# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flaskud2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3474943511cd48029460472c3b877439 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_49e6b7d5bc544bedab1b04f47c5b846f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3474943511cd48029460472c3b877439 }}/flaskapp2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flaskud2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_520d18d5b28b44338c2e88041713a488 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3474943511cd48029460472c3b877439 }}/flaskapp2:${{ github.sha }}'